### ISSUE TITLE
Only one unused-using is removed at a time.

### ISSUE THREAD

**Issue by altnp** [JeremyCaron/vscode-csharp-organize-usings#17] opened 2024-11-24 05:02 UTC
VS Code 1.95.3
Windows & Windows WSL
All default settings

Only one unused using is removed per execution of the organize usings command.

**Comment by JeremyCaron** [comment] 2024-11-25 14:34
Interesting, must be a C# dev kit thing because I've never tried it with that setup due to the licensing situation that extension requires. Will do so with a non-commercial codebase though to see if I can repro.

**Comment by JeremyCaron** [comment] 2024-11-25 21:38
I installed the C# dev kit, relaunched vscode, confirmed it was using the dev kit language server, and I still could not reproduce.  Next best guess is there's something different about the codebase we're working with.

I have this random C# repro checked out to test with: https://github.com/Cysharp/ConsoleAppFramework.git

I added three unused usings to EquatableArray and all three are removed when I run the extension (I'm setup to run on save, but it also works when I execute it from the command palette):

Before:
![image](https://github.com/user-attachments/assets/30bcbf01-a287-47c6-a958-922b3e78d3d8)

After:
![image](https://github.com/user-attachments/assets/b1c224aa-4f3a-496a-98e7-25be3d32e424)

Could you try this with the code base above to see if it works or doesn't on your machine with this specific test case?

It would be awesome if you could capture a quick screen recording of what you're seeing (slack has a basic screen recorder built-in if you don't have another one installed) because I'm at a loss for ideas as to what to try next in order to repro :confused:

**Comment by JeremyCaron** [comment] 2024-11-26 04:20
Ooh, I may have found a repro case with this:

![image](https://github.com/user-attachments/assets/9235f656-c8e7-4ee5-85ae-5bbe552641fd)

After:

![image](https://github.com/user-attachments/assets/18ec85b6-f3ae-4fb5-9965-df8f4ce1a8db)

Is this a more realistic example of what you've been seeing, where the unused usings that are left behind are in different groups of usings statements @altnp?

**Comment by JeremyCaron** [comment] 2024-11-26 04:47
Caught the root cause in the debugger, this seems like a case where what works under Omnisharp/Roslyn just doesn't in Dev Kit due to a borked implementation of vs.languages.getDiagnostics.  For exactly the case above, it only returns 3 diagnostics instead of the 4 that would be expected for the 4 grayed-out usings in the editor (the debug panel to the left shows three items in the diagnostics variable):

![image](https://github.com/user-attachments/assets/bea3af74-aafe-44b8-a06e-00f8855a0443)

These values are what drives the lines that get removed, so unless MS provides a fix here I don't think there's much I can do.  Will poke at it a bit more to try to confirm though and will add something to the README about C# Dev Kit support if I don't have any luck.

**Comment by JeremyCaron** [comment] 2024-11-26 06:07
Figured it out @altnp, there was a pretty significant misunderstanding of how the ranges on the diagnostics work (and that a diagnostic can cover multiple consecutive lines).  I'll try to ship a fix before Thanksgiving hits.

Thanks again for the report.

**Comment by altnp** [comment] 2024-11-26 07:06
Awesome, appreciate it! On Nov 26, 2024, at 1:08 AM, JeremyCaron ***@***.***> wrote:﻿
Figured it out @altnp, there was a pretty significant misunderstanding of how the ranges on the diagnostics work (and that a diagnostic can cover multiple consecutive lines).  I'll try to ship a fix before Thanksgiving hits.
Thanks again for the report.

**Comment by JeremyCaron** [comment] 2024-11-27 03:50
Version 1.0.6 has been released which should resolve this.  Going to close this ticket @altnp but definitely let me know if this doesn't fix it for you.

**Closed by JeremyCaron** 2024-11-27 03:50 UTC
Labels: bug, question
